name: 'Pull Request auto size labeler'
description: 'Github action to automatically add label on PR to define size (based on line diff and file modified)'
author: 'BedrockStreaming'
branding:
  icon: 'award'
  color: 'green'
inputs:
  xs_label:
    description: 'XS label text'
    required: false
    default: 'Size/XS'
  xs_diff:
    description: 'Size of line diff for XS label'
    required: false
    default: '50'
  xs_files:
    description: 'Size of file diff for XS label'
    required: false
    default: '5'
  s_label:
    description: 'S label text'
    required: false
    default: 'Size/S'
  s_diff:
    description: 'Size of line diff for S label'
    required: false
    default: '100'
  s_files:
    description: 'Size of file diff for S label'
    required: false
    default: '10'
  m_label:
    description: 'M label text'
    required: false
    default: 'Size/M'
  m_diff:
    description: 'Size of line diff for M label'
    required: false
    default: '500'
  m_files:
    description: 'Size of file diff for M label'
    required: false
    default: '30'
  l_label:
    description: 'L label text'
    required: false
    default: 'Size/L'
  l_diff:
    description: 'Size of line diff for L label'
    required: false
    default: '800'
  l_files:
    description: 'Size of file diff for L label'
    required: false
    default: '50'
  xl_label:
    description: 'XL label text'
    required: false
    default: 'Size/XL'
  xl_diff:
    description: 'Size of line diff for XL label'
    required: false
    default: '1500'
  xl_files:
    description: 'Size of file diff for XL label'
    required: false
    default: '100'
  exclude_files:
    description: 'Regexp to ignore files from the line diff count (example: yarn.lock)'
    required: true
  token:
    description: 'Github API token'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
